version: 2.1

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build-linux

jobs:
  build-linux:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run:
          name: build
          command: go build .
